var annotated_dup =
[
    [ "m5avatar", null, [
      [ "Avatar", "classm5avatar_1_1_avatar.html", "classm5avatar_1_1_avatar" ],
      [ "Balloon", "classm5avatar_1_1_balloon.html", null ],
      [ "BaseEye", "classm5avatar_1_1_base_eye.html", null ],
      [ "BaseEyebrow", "classm5avatar_1_1_base_eyebrow.html", null ],
      [ "BaseMouth", "classm5avatar_1_1_base_mouth.html", null ],
      [ "BatteryIcon", "classm5avatar_1_1_battery_icon.html", null ],
      [ "BMPEye", "classm5avatar_1_1_b_m_p_eye.html", null ],
      [ "BMPFace", "classm5avatar_1_1_b_m_p_face.html", null ],
      [ "BoundingRect", "classm5avatar_1_1_bounding_rect.html", null ],
      [ "BowEyebrow", "classm5avatar_1_1_bow_eyebrow.html", null ],
      [ "ColorPalette", "classm5avatar_1_1_color_palette.html", null ],
      [ "DogEye", "classm5avatar_1_1_dog_eye.html", null ],
      [ "DogFace", "classm5avatar_1_1_dog_face.html", null ],
      [ "DoggyEye", "classm5avatar_1_1_doggy_eye.html", null ],
      [ "DoggyFace", "classm5avatar_1_1_doggy_face.html", null ],
      [ "DoggyMouth", "classm5avatar_1_1_doggy_mouth.html", null ],
      [ "DogMouth", "classm5avatar_1_1_dog_mouth.html", null ],
      [ "Drawable", "classm5avatar_1_1_drawable.html", null ],
      [ "DrawContext", "classm5avatar_1_1_draw_context.html", null ],
      [ "DriveContext", "classm5avatar_1_1_drive_context.html", null ],
      [ "Effect", "classm5avatar_1_1_effect.html", null ],
      [ "EllipseEye", "classm5avatar_1_1_ellipse_eye.html", null ],
      [ "EllipseEyebrow", "classm5avatar_1_1_ellipse_eyebrow.html", null ],
      [ "Eye", "classm5avatar_1_1_eye.html", null ],
      [ "Eyeblow", "classm5avatar_1_1_eyeblow.html", null ],
      [ "Face", "classm5avatar_1_1_face.html", null ],
      [ "Gaze", "classm5avatar_1_1_gaze.html", null ],
      [ "GirlyEye", "classm5avatar_1_1_girly_eye.html", null ],
      [ "GirlyFace", "classm5avatar_1_1_girly_face.html", null ],
      [ "GirlyFace2", "classm5avatar_1_1_girly_face2.html", null ],
      [ "Mouth", "classm5avatar_1_1_mouth.html", null ],
      [ "OledFace", "classm5avatar_1_1_oled_face.html", null ],
      [ "OmegaFace", "classm5avatar_1_1_omega_face.html", null ],
      [ "OmegaMouth", "classm5avatar_1_1_omega_mouth.html", null ],
      [ "PinkDemonEye", "classm5avatar_1_1_pink_demon_eye.html", null ],
      [ "PinkDemonFace", "classm5avatar_1_1_pink_demon_face.html", null ],
      [ "RectEyebrow", "classm5avatar_1_1_rect_eyebrow.html", null ],
      [ "RectMouth", "classm5avatar_1_1_rect_mouth.html", null ],
      [ "SimpleFace", "classm5avatar_1_1_simple_face.html", null ],
      [ "UShapeMouth", "classm5avatar_1_1_u_shape_mouth.html", null ]
    ] ]
];